### PR TITLE
Support for Nova 4

### PR DESCRIPTION
**Pull request by crynobone**
image

### CODE REVIEW

**Comment by repat** [comment]
@freekmurze could you take a look at this? :)

**Comment by freekmurze** [comment]
I'm waiting a bit until @crynobone marks this as ready.

Please be patient, as with Nova 4 being released, there's probably a lot of support work that needs to be done there.

**Comment by Gummibeer** [comment]
Have tested the branch in one of my projects and everything works just fine. 🎉🚀

**Comment by crynobone** [comment]
Thank @Gummibeer 

@freekmurze I believe it might be best to release it as it is and deal with CSS improvement later on.

**Comment by freekmurze** [comment]
Thanks @crynobone for your work on this, and thanks @Gummibeer for testing. You're both awesome! 👍

**Comment by Gummibeer** [comment]
I would recommend a rc.1 release first - that way I can test it on production as well.

**Comment by freekmurze** [comment]
lol, too late, already released 🚀

**Comment by Gummibeer** [comment]
Also works with the new branding options. 🎉

Kraken-Life-Backups

**Pull request merged**
