### PR TITLE
Fixes Tool Page Title

### PR DESCRIPTION
**Pull request by aryehraber**
It seems PR https://github.com/spatie/nova-backup-tool/pull/108 tried adding a Page Title to the Backup Tool, however it doesn't work due to a missing reference to the `__()` method. 

This is the error I'm seeing in Nova when visiting the Backup Tool:
Screenshot 2022-01-13 at 09 49 45

Since the `__()` is bound to the Vue instance, it needs to be `this.__()`. Let me know if there are any questions, thanks!

### CODE REVIEW

**Comment by aryehraber** [comment]
Hi Spatie team, please let me know if there's any feedback to get this merged, happy to make changes is needed!

**Comment by freekmurze** [comment]
Could you resolve the conflicts?

**Comment by aryehraber** [comment]
Sure thing, must be due to the other PR that was just merged -- will get sorted asap!

**Comment by aryehraber** [comment]
Alright, rebased from master and rebuilt the assets -- should be good to go now!

(not sure why the tests are failing, don't think this has to do with the PR)

**Comment by freekmurze** [comment]
Thank you!

**Pull request merged**
