### PR TITLE
Allow spatie backup 7.x #91

### PR DESCRIPTION
**Pull request by spekulatius**
Hello @freekmurze 

I've started the upgrade for #91. There might be still parts open to do. I open a PR to run the tests and to discuss any changes required. 

Cheers,
Peter

### CODE REVIEW

**Comment by spekulatius** [comment]
One question: How can we run the test for this with GH actions here @freekmurze ?

**Comment by freekmurze** [comment]
I don't have time to fix the tests at this point, but if you guarantee that the changes work well for you, I'll merge and tag it!

**Comment by spekulatius** [comment]
Hello @freekmurze 

I'm happy to support debugging issues as far as I can. 

There are two known differences for me: I've increased the polling time to 60 seconds as my backup backend seems to be a bit too slow. But this shouldn't cause (new) issues for others. Similarly, the backup job times out and I got to increase this - but that's environment specific and shouldn't be a problem with the package.

Cheers,
Peter

**Comment by freekmurze** [comment]
Thanks!

**Comment by spekulatius** [comment]
No worries!

**Pull request merged**
